class IconFixer {
  static String fix(String content) {
    Map<String, String> iconReplacements = {
      'Icons.target': 'Icons.gps_fixed',
      'Icons.competition': 'Icons.sports',
      'Icons.forecast': 'Icons.trending_up',
      'Icons.factor': 'Icons.analytics',
      'Icons.calculator': 'Icons.calculate',
      'Icons.schedule_delete': 'Icons.schedule',
      'Icons.template_outlined': 'Icons.description',
      'Icons.atom': 'Icons.science',
      'Icons.test_tube': 'Icons.biotech',
      'Icons.sword': 'Icons.sports_esports',
      'Icons.no_ads': 'Icons.block',
      'Icons.dragon': 'Icons.pets',
      'Icons.concierge_mopeds': 'Icons.room_service',
      'Icons.investigation': 'Icons.search',
      'Icons.check_list': 'Icons.checklist',
      'Icons.efficiency': 'Icons.speed',
      'Icons.bounce_email': 'Icons.email',
      'Icons.road': 'Icons.directions',
      'Icons.door_front': 'Icons.door_front_door',
      'Icons.simplify': 'Icons.minimize',
      'Icons.interactive_space': 'Icons.touch_app',
      'Icons.live_tv_off': 'Icons.tv_off',
      'Icons.replay_15': 'Icons.replay',
      'Icons.forward_15': 'Icons.forward',
      'Icons.sleep_timer': 'Icons.bedtime',
      'Icons.background_replace': 'Icons.wallpaper',
      'Icons.edge': 'Icons.crop',
      'Icons.clarity': 'Icons.tune',
      'Icons.shapes': 'Icons.category',
      'Icons.oval': 'Icons.circle',
      'Icons.available_for_sale': 'Icons.sell',
      'Icons.shopping_mall': 'Icons.shopping_cart',
      'Icons.concierge_care': 'Icons.support_agent',
      'Icons.no_shoes': 'Icons.no_cell',
      'Icons.luxury_dining': 'Icons.restaurant',
      'Icons.person_check': 'Icons.person_add',
      'Icons.test_outlined': 'Icons.quiz',
      'Icons.cable_car': 'Icons.cable',
      'Icons.calendar_view_year': 'Icons.calendar_today',
      'Icons.template_filled': 'Icons.description',
      'Icons.impact': 'Icons.flash_on',
      'Icons.calendar_week': 'Icons.date_range',
      'Icons.mail_open': 'Icons.mail',
      'Icons.camping': 'Icons.outdoor_grill',
      'Icons.activity_zone': 'Icons.sports',
      'Icons.platform': 'Icons.computer',
      'Icons.platform_shape': 'Icons.shape_line',
      'Icons.award': 'Icons.emoji_events',
      'Icons.google': 'Icons.g_mobiledata',
      'Icons.flatten': 'Icons.layers',
      'Icons.timer_2': 'Icons.timer',
      'Icons.timer_5': 'Icons.timer',
      'Icons.template_add': 'Icons.add',
      'Icons.people_off': 'Icons.people',
      'Icons.shopping_cart_off': 'Icons.shopping_cart',
      'Icons.receipt_long_off': 'Icons.receipt',
      'Icons.description_off': 'Icons.description',
      'Icons.payment_off': 'Icons.payment',
      'Icons.communication': 'Icons.chat',
      'Icons.file_export': 'Icons.file_download',
      'Icons.carbon_dioxide': 'Icons.eco',
      'Icons.bounce_rate': 'Icons.trending_down',
      'Icons.conversion': 'Icons.trending_up',
      'Icons.remote_control': 'Icons.settings_remote',
      'Icons.urgent': 'Icons.priority_high',
      'Icons.schedule_problem': 'Icons.error',
      'Icons.presentation': 'Icons.slideshow',
      'Icons.automation': 'Icons.auto_awesome',
      'Icons.lightning_bolt': 'Icons.flash_on',
      'Icons.funnel_chart': 'Icons.filter_list',
      'Icons.microsoft': 'Icons.computer',
      'Icons.sitemap': 'Icons.account_tree',
      'Icons.draft': 'Icons.edit',
      'Icons.innovation': 'Icons.lightbulb',
      'Icons.usage': 'Icons.usage',
      'Icons.shopping_list': 'Icons.list',
      'Icons.signature': 'Icons.edit',
      'Icons.lifestyle': 'Icons.favorite',
      'Icons.exercise': 'Icons.fitness_center',
      'Icons.pain_relief': 'Icons.healing',
      'Icons.dental_care': 'Icons.medical_services',
      'Icons.brain': 'Icons.psychology',
      'Icons.price_tag': 'Icons.local_offer',
      'Icons.factor_outlined': 'Icons.analytics',
      'Icons.accuracy': 'Icons.check_circle',
      'Icons.manual_mode': 'Icons.touch_app',
      'Icons.quality_check': 'Icons.verified',
      'Icons.write': 'Icons.edit',
      'Icons.software': 'Icons.apps',
      'Icons.license': 'Icons.assignment',
      'Icons.spray': 'Icons.format_paint',
      'Icons.prediction': 'Icons.psychology',
      'Icons.visit_history': 'Icons.history',
      'Icons.hybrid_outlined': 'Icons.merge_type',
      'Icons.screen_record': 'Icons.screen_share',
      'Icons.investment': 'Icons.trending_up',
      'Icons.moderation': 'Icons.admin_panel_settings',
      'Icons.rpc_outlined': 'Icons.api',
      'Icons.rules': 'Icons.rule',
      'Icons.reassignment': 'Icons.assignment_ind',
      'Icons.export_notes': 'Icons.file_download',
      'Icons.sprint': 'Icons.directions_run',
      'Icons.gaming_outlined': 'Icons.games',
      'Icons.hurricane': 'Icons.waves',
      'Icons.air_purifier_outlined': 'Icons.air',

    };

    String fixedContent = content;

    iconReplacements.forEach((oldIcon, newIcon) {
      fixedContent = fixedContent.replaceAll("${oldIcon},", "${newIcon},");
      fixedContent = fixedContent.replaceAll("${oldIcon})", "${newIcon})");
      fixedContent = fixedContent.replaceAll("${oldIcon}}", "${newIcon}}");
      fixedContent = fixedContent.replaceAll("${oldIcon}]", "${newIcon}]");
      fixedContent = fixedContent.replaceAll("${oldIcon};", "${newIcon};");
      fixedContent = fixedContent.replaceAll("${oldIcon} ", "${newIcon} ");
      fixedContent = fixedContent.replaceAll("${oldIcon}\n", "${newIcon}\n");
    });

    return fixedContent;
  }
}
